export const ACTION_EVALUATIONS_FETCH = 'ACTION_EVALUATIONS_FETCH';
export const ACTION_EVALUATIONS_GET = 'ACTION_EVALUATIONS_GET';
export const ACTION_EVALUATIONS_CREATE = 'ACTION_EVALUATIONS_CREATE';