export const ACTION_EVALUATIONS_FETCH_SUCCESS = 'ACTION_EVALUATIONS_FETCH_SUCCESS';
export const ACTION_EVALUATIONS_FETCH_FAIL = 'ACTION_EVALUATIONS_FETCH_FAIL';

export const ACTION_EVALUATIONS_GET_SUCCESS = 'ACTION_EVALUATIONS_GET_SUCCESS';
export const ACTION_EVALUATIONS_GET_FAIL = 'ACTION_EVALUATIONS_GET_FAIL';

export const ACTION_EVALUATIONS_CREATE_SUCCESS = 'ACTION_EVALUATIONS_CREATE_SUCCESS';
export const ACTION_EVALUATIONS_CREATE_FAIL = 'ACTION_EVALUATIONS_CREATE_FAIL';
